apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque # Tipe standar untuk key-value rahasia
data:
  DB_PASSWORD: cmFoYXNpYTEyMw== # Nilai "rahasia123" versi base64
  JWT_SECRET: c3VwZXJzZWNyZXQ= # Nilai "supersecret" versi base64
